controller_manager:
  ros__parameters:
    update_rate: 30  # Hz
    use_sim_time: True
    slider_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    diff_cont:
      type: diff_drive_controller/DiffDriveController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    caster_wheel_controller:
      type: effort_controllers/JointGroupEffortController

slider_controller:
  ros__parameters:
    joints:
      - slider
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
diff_cont:
  ros__parameters:

    publish_rate: 30.0 
    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.37
    wheel_radius: 0.08

    use_stamped_vel: false
caster_wheel_controller:
  ros__parameters:
    joints:
      - Revolute 20
      - Revolute 21
      - Revolute 22
      - Revolute 23
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
