controller_manager:
  ros__parameters:
    update_rate: 30  # Hz
    use_sim_time: true
    slider_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    diff_cont:
      type: diff_drive_controller/DiffDriveController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

slider_controller:
  ros__parameters:
    joints:
      - slider
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
diff_cont:
  ros__parameters:

    publish_rate: 30.0 
    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.21
    wheel_radius: 0.075

    use_stamped_vel: false
