controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true
    slider_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    diff_cont:
      type: diff_drive_controller/DiffDriveController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    caster_wheel_controller:
      type: effort_controllers/JointGroupEffortController
      
    arm_controller:
      type: effort_controllers/JointGroupEffortController

slider_controller:
  ros__parameters:
    joints:
      - slider
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
diff_cont:
  ros__parameters:

    publish_rate: 1000.0 
    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.37
    wheel_radius: 0.08

    use_stamped_vel: false
caster_wheel_controller:
  ros__parameters:
    joints:
      - castor_1
      - castor_2
      - castor_3
      - castor_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
arm_controller:
  ros__parameters:
    joints:
      - shoulder_joint
      - upperarm_joint
      - forearm_joint
      - wrist_joint_1
      - wrist_joint_2
      - wrist_joint_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
